export const CONTACTUS_EMAIL = 'info@guillendentalcare.com'
export const FIXED_NUMBER = '+506 83035477'
export const WHATSUP_NUMBER = '+506 83035477'
export const WHATSUP_NUMBER_LINK = 'https://wa.me/50683035477?text=Hola%20estoy%20interesado%20en%20agendar%20una%20cita%20con%20Guillén%20DentalCare'
export const WAZE_DIRETION = 'https://ul.waze.com/ul?place=ChIJrwX5DXzjoI8RKbAltTNpSeU&ll=9.93493630%2C-84.06313110&navigate=yes&utm_campaign=default&utm_source=waze_website&utm_medium=lm_share_location'
export const MAPS_DIRECTION = 'https://maps.app.goo.gl/TFtHYLVMkoNn3TNe9'
export const FACEBOOK_LINK = 'https://www.facebook.com/guillen.dental.care/'
export const INSTAGRAM_LINK = 'https://www.instagram.com/guillen.dental.care/?hl=es'
export const TIKTOK_LINK = 'https://www.tiktok.com/@ortodoncia.guillendental'